server:
  port: 8001
 
spring:
  application:
    name: spring-cloud-common
 
eureka:
  instance:
    instance-id: spring-cloud-common
    appname: ${spring.application.name}
  client: 
    service-url: 
      defaultZone: http://127.0.0.1:8888/eureka/
